version: '3'
services:
  filebeat:
    image: prima/filebeat 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/filebeat.yml:/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
